### ISSUE TITLE
RC2 has no future. IV:MP is still 95% 0.1-T3 based.

### ISSUE THREAD

**Issue by treboR-0** [GTA-Network/IV-Network#91]
All due respect to RC2 and where it Could have gone. IV:MP is still 95% 0.1-T3 based, And given this bias, no backwards compatibility, and lack of future development for RC2, IV:Multiplayer will forever be 0.1-T3 based. Thanks for making RC2 Open Source, but that doesn't help anyone. If it was your intention to help, make the final version of 0.1-T3 Open Source as well, for RC2 has no future.

**Comment by treboR-0** [comment]
Closing an issue is not a resolution. IV:MP a nanos claimed network,
abandoned to its own, deserves more than... issue closed. RC2 is an
unusable upgrade, it doesn't function, it looks nice enough but all
cars spawn irrevocably at the 0 0 0  club and are irretrievable, as
though it were sabotaged. AS a result IV:MPs 2500+ users all use the
last stable functioning version, IV:MPs only used client 0.1-T3 which
is not compatible with this version RC2 therefore Rc2 not only does
not work, it is also useless. Please make 0.1-T3 source available.

**Comment by Rukenshia** [comment]
You can check the 0.1-T3 version out on your own by going back through the history. We do not have any records of the 0.1T3 HEAD commit hash, so we can't help you. The project has been discontinued and is no longer supported.

**Comment by Rukenshia** [comment]
alternatively, try the archive of the original iv-multiplayer repository: https://code.google.com/archive/p/ivmultiplayer/
